var deque_module = require('./deque.js');
var dq = new deque_module();
console.log("Front is " + dq.readFront());
dq.pushBack(23);
dq.pushBack(34);
dq.pushBack(38);
dq.pushBack(48);
dq.pushBack(1);
dq.pushBack(2);
dq.pushBack(3);
dq.pushBack(4);
console.log("Front is " + dq.readFront());
console.log("Front is " + dq.readFront());
console.log("readIndexFromFront 2 is " + dq.readIndexFromFront(2));
console.log("readIndexFromBack 0 is " + dq.readIndexFromBack(0));
console.log("readIndexFromBack 1 is " + dq.readIndexFromBack(1));
console.log("size is " + dq.size());
